// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: contact.sql

package sqlc

import (
	"context"
)

const newMessage = `-- name: NewMessage :one
INSERT INTO contact (account, message_body)
VALUES ($1, $2)
RETURNING id, account, message_body
`

type NewMessageParams struct {
	Account     int64  `json:"account"`
	MessageBody string `json:"message_body"`
}

func (q *Queries) NewMessage(ctx context.Context, arg NewMessageParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, newMessage, arg.Account, arg.MessageBody)
	var i Contact
	err := row.Scan(&i.ID, &i.Account, &i.MessageBody)
	return i, err
}
