// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: public_shared_collection.sql

package sqlc

import (
	"context"
	"database/sql"
)

const shareCollectionWithPublicLink = `-- name: ShareCollectionWithPublicLink :one
INSERT INTO public_shared_collection (collection_id, collection_password, collection_shared_by, collection_share_expiry, collection_access_level)
VALUES ($1, $2, $3, $4, $5)
RETURNING collection_id, collection_password, collection_shared_by, collection_shared_at, collection_share_expiry, collection_access_level
`

type ShareCollectionWithPublicLinkParams struct {
	CollectionID          string                `json:"collection_id"`
	CollectionPassword    string                `json:"collection_password"`
	CollectionSharedBy    int64                 `json:"collection_shared_by"`
	CollectionShareExpiry sql.NullTime          `json:"collection_share_expiry"`
	CollectionAccessLevel CollectionAccessLevel `json:"collection_access_level"`
}

func (q *Queries) ShareCollectionWithPublicLink(ctx context.Context, arg ShareCollectionWithPublicLinkParams) (PublicSharedCollection, error) {
	row := q.db.QueryRowContext(ctx, shareCollectionWithPublicLink,
		arg.CollectionID,
		arg.CollectionPassword,
		arg.CollectionSharedBy,
		arg.CollectionShareExpiry,
		arg.CollectionAccessLevel,
	)
	var i PublicSharedCollection
	err := row.Scan(
		&i.CollectionID,
		&i.CollectionPassword,
		&i.CollectionSharedBy,
		&i.CollectionSharedAt,
		&i.CollectionShareExpiry,
		&i.CollectionAccessLevel,
	)
	return i, err
}
